# Generated by Django 5.0.1 on 2024-02-01 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='profile_dp',
        ),
    ]
