# Generated by Django 5.0.1 on 2024-02-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_useraccount_profile_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(max_length=499, unique=True, verbose_name='email field'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='fname',
            field=models.CharField(max_length=499),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='lname',
            field=models.CharField(blank=True, max_length=499),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.CharField(max_length=499, unique=True),
        ),
    ]
